name: Nightly Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_type: Debug
            compiler: gcc
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            build_type: Release
            compiler: gcc
            cc: gcc
            cxx: g++
          # - os: ubuntu-latest
          #   build_type: Debug
          #   compiler: clang
          #   cc: clang
          #   cxx: clang++
          # - os: ubuntu-latest
          #   build_type: Release
          #   compiler: clang
          #   cc: clang
          #   cxx: clang++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: latest

    - name: Install HL haxelib
      run: haxelib install hashlink

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev \
          libsdl2-dev libglu1-mesa-dev libmbedtls-dev libuv1-dev \
          libsqlite3-dev ninja-build patchelf

    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
      run: |
          cmake -S hlmod-hl -B hlmod-hl/build -G "Ninja" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build with CMake
      run: cmake --build hlmod-hl/build --parallel

    - name: Build hlsteam (Linux)
      if: runner.os == 'Linux'
      env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
      run: |
          mkdir -p hlsteam/native/include/steam
          mkdir -p hlsteam/native/lib/linux64
          cp ./Steamworks-SDK/public/steam/*.h hlsteam/native/include/steam/
          cp ./Steamworks-SDK/redistributable_bin/linux64/libsteam_api.so hlsteam/native/lib/linux64/
          cp ./hlmod-hl/src/hl.h hlsteam/native/include/
          
          cd hlsteam
          make CXXFLAGS="-Inative/include" LFLAGS="-L../hlmod-hl/build/bin"
          cd ..

          cp ./hlsteam/steam.hdll ./hlmod-hl/build/bin/
          patchelf --set-rpath '$ORIGIN' ./hlmod-hl/build/bin/steam.hdll
          cp ./Steamworks-SDK/redistributable_bin/linux64/libsteam_api.so ./hlmod-hl/build/bin/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: hlmod-hl-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}
          path: hlmod-hl/build/bin/